### ISSUE TITLE
Establish communication between ESP8266 and RPI

### ISSUE THREAD

**Issue by davidsarrat** [GarduinoTeam/Garduino#96]

**Comment by Rochii** [comment]
The RPi and ESP8266 uses the MQTT protocol to comunicate. 

MQTT relies on the TCP protocol for data transmission. A variant, MQTT-SN, is used over other transports such as UDP or Bluetooth. MQTT sends connection credentials in plain text format and does not include any measures for security or authentication.

Succesful communication.
